name: Samsung EROFS to EXT4
on:
  push:
    branches:
      - main  # Change this to your desired branch
  workflow_dispatch:
    inputs:
      GSI:
        description: 'Samfw Link For AP'
        required: true
        default: 'AP LINK'
      
      System:
        description: 'GSI system.img'
        required: true
        default: 'Link to system.img'

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y cpio bc simg2img lz4 git device-tree-compiler lz4 xz-utils zlib1g-dev openjdk-17-jdk gcc g++ python3 python-is-python3 p7zip-full android-sdk-libsparse-utils erofs-utils
        sudo apt install -y zip xz-utils unzip p7zip-full wget
        
    - name: Preparing Files
      run: |
        # Downloading and extracting necessary files
        wget https://github.com/Ping-1/RepackAP/blob/main/v5_super_repacker.zip
        wget https://github.com/VeloshGSIs/Super_Guide/blob/master/lpunpack
        wget https://github.com/VeloshGSIs/Super_Guide/blob/master/imjtool
        unzip v5_super_repacker.zip
        rm -r v5_super_repacker.zip

    - name: Downloading given firmware
      run: |
        # Downloading Stock rom
        wget -O ap.zip ${{ github.event.inputs.GSI }} 
        #chmod +x *
        #chmod 755 bin/*
        #chmod 755 aik/bin/*

    - name: Downloading given system.img
      run: |
        wget ${{ github.event.inputs.System }} 

    - name: Integrating
      run: |
        unzip ap.zip
        sudo ./imjtool super.img extract
        sudo ./lpunpack super.ext4.img

    - name: Rename file
      run: mv ./last/EXT4_RW_AP.zip ./last/${{ github.event.inputs.Firmware }}.zip

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: EXT4_RW_AP
        path: ./last/${{ github.event.inputs.Firmware }}.zip
