name: RepackAP
on:
  push:
    branches:
      - main  # Change this to your desired branch
  workflow_dispatch:
    inputs:
      GSI:
        description: 'Samfw Link For AP'
        required: true
        default: 'AP LINK'
      
      System:
        description: 'GSI system.img'
        required: true
        default: 'Link to system.img'

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y cpio bc simg2img lz4 git device-tree-compiler lz4 xz-utils zlib1g-dev openjdk-17-jdk gcc g++ python3 python-is-python3 p7zip-full android-sdk-libsparse-utils erofs-utils
        sudo apt install -y zip xz-utils unzip p7zip-full wget 
        
    - name: Preparing Files
      run: |
        # Downloading and extracting necessary files
        #wget https://github.com/Ping-1/RepackAP/blob/main/v5_super_repacker.zip
        #wget https://github.com/VeloshGSIs/Super_Guide/blob/master/lpunpack
        #wget https://github.com/VeloshGSIs/Super_Guide/blob/master/imjtool
        wget newandroidbook.com/tools/imjtool.tgz
        mkdir ./imjtool_tmp
        tar -xf imjtool.tgz -C ./imjtool_tmp
        cp ./imjtool_tmp/imjtool.ELF64 ./imjtool
        rm -rf ./imjtool_tmp imjtool.tgz
        sudo apt install clang zlib1g-dev
        git clone https://github.com/LonelyFool/lpunpack_and_lpmake.git
        cd lpunpack_and_lpmake/ && ./make.sh && cd ..
        cp ./lpunpack_and_lpmake/bin/lpunpack ./
        cp ./lpunpack_and_lpmake/bin/lpmake ./
        rm -rf ./lpunpack_and_lpmake
        unzip v5_super_repacker.zip
        rm -r v5_super_repacker.zip

    - name: Downloading given firmware
      run: |
        # Downloading Stock rom
        wget -O ap.zip ${{ github.event.inputs.GSI }} 
        #chmod +x *
        #chmod 755 bin/*
        #chmod 755 aik/bin/*

    - name: Downloading given system.img
      run: |
        wget -O gsi.img ${{ github.event.inputs.System }} 

    - name: Integrating
      run: |
        unzip ap.zip
        lz4 -d super.img.lz4 super.img
        sudo simg2img super.img superraw.img
        imjtool.ELF64 superraw.img extract
        rm -r system.img
        mv ./gsi.img ./system.img
        super_path="super.img"
        system_path="system.img"
        odm_path="odm.img"
        vendor_path="vendor.img"
        product_path="product.img"
        super_size=$(stat -c "%s" "$super_path")
        system_size=$(stat -c "%s" "$system_path")
        product_size=$(stat -c "%s" "$product_path")
        vendor_size=$(stat -c "%s" "$vendor_path")
        odm_size=$(stat -c "%s" "$odm_path")
        lpmake --metadata-size 65536 --super-name super --metadata-slots 2 --device super:$super_size --group main:$sum --partition system:readonly:$system_size:main --image system=$system_path --partition vendor:readonly:$vendor_size:main --image vendor=$vendor_path --partition product:readonly:$product_size:main --image product=$product_path --partition odm:readonly:$odm_size:main --image odm=$odm_path --sparse --output ./super.new.img
         mv super.new.img super.img
         tar -cfv repackap.tar boot.img.lz4 vbmeta.img.lz4 super.img
         zip repackap.zip -r ./*
        

#    - name: Rename file
#      run: mv ./last/#EXT4_RW_system_path="out_ext4/system.new.img"
#odm_path="out_ext4/odm.new.img"
#vendor_path="out_ext4/vendor.new.img"
#product_path="out_ext4/#product.new.img"AP.zip ./last/${{ github.event.inputs.Firmware }}.zip

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: RepackAP
        path: ./last/repackap.zip
